import { Player } from '../types';

export const defaultPlayers: Player[] = [
  {
    id: 'me',
    name: 'Admin',
    role: 'Operator',
    email: 'admin@dusk.gg',
    tags: ['operator', 'core'],
    favorite: true,
    timeZone: 'Asia/Makassar',
    permissions: {
      profileLevel: 'details',
      location: 'live',
      pinVisibility: 'specific',
      rankVisibility: true,
      appearsInRank: true,
      closeCircle: true,
    },
    accepted: true,
  },
  {
    id: 'p1',
    name: 'Nova',
    role: 'Recon',
    favorite: true,
    tags: ['friend', 'field', 'close'],
    email: 'nova@xtation.local',
    phone: '+1 415 555 0108',
    timeZone: 'America/Los_Angeles',
    location: { lat: 37.7764, lng: -122.4172, label: 'San Francisco' },
    permissions: {
      profileLevel: 'basic',
      location: 'city',
      pinVisibility: 'close',
      rankVisibility: true,
      appearsInRank: true,
      closeCircle: true,
    },
    accepted: true,
  },
  {
    id: 'p2',
    name: 'Echo',
    role: 'Support',
    tags: ['support', 'work'],
    email: 'echo@xtation.local',
    timeZone: 'Europe/Berlin',
    permissions: {
      profileLevel: 'details',
      location: 'off',
      pinVisibility: 'specific',
      rankVisibility: true,
      appearsInRank: true,
      closeCircle: false,
    },
    accepted: false,
  },
  {
    id: 'p3',
    name: 'Atlas',
    role: 'Strategist',
    tags: ['systems', 'planning'],
    email: 'atlas@xtation.local',
    phone: '+62 812 5550 1188',
    timeZone: 'Asia/Singapore',
    location: { lat: 1.3521, lng: 103.8198, label: 'Singapore' },
    permissions: {
      profileLevel: 'details',
      location: 'city',
      pinVisibility: 'specific',
      rankVisibility: true,
      appearsInRank: true,
      closeCircle: false,
    },
    accepted: true,
  },
];
